name: Upload To Dropbox
on: [push, pull_request]

jobs:
  upload-to-dropbox:
    runs-on: "ubuntu-latest"
    name: Upload to dropbox
    
    steps:
      - name: deka dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: bin/*
          dest: /git-builds/
          multiple: true
